### ISSUE TITLE
v1.0.0 release

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#181]
This is ticket for collecting blocking issues, ideas and other requirements for a 1.0.0 release of the openEO python client

**Comment by soxofaan** [comment]
Some first suggestions (feel free to disagree and comment):

- [ ] do a full sweep of all tickets to see what is still valid and needs addressing
- [ ] #134 #105  Drop API v0.4 support: so that we can get rid of all the dead weight related to that
- [ ] #115 #100  clean up other deprecated/outdated left-overs
- [ ] #111 clean up and harmonize examples
- [ ] further improve usability of OpenID Connect functionality?
- [ ] #174   jupyter integration
- [ ]  resolve the dependency graph problem related to developing UDFs locally #159 #169

**Comment by soxofaan** [comment]
- [ ] #217  Remove band-to-index conversion feature in cube.band() band math method

**Comment by soxofaan** [comment]
[ ] https://github.com/Open-EO/openeo-python-client/issues/239

**Comment by soxofaan** [comment]
- #280

**Comment by soxofaan** [comment]
- [ ] #300

**Comment by soxofaan** [comment]
- https://github.com/Open-EO/openeo-python-client/issues/312
